apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: bananaops/tracker
      docker:
        dockerfile: Dockerfile
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
      - name: tracker-dev
        chartPath: helm/tracker
        namespace: tracker
        createNamespace: true
        artifactOverrides:
          image: bananaops/tracker
        imageStrategy:
          helm: {}
        setValues:
          env.jira.domain: "jira.company.com"
          env.jira.projectKey: "PROJ"
          env.slack.workspace: "your-workspace"
